---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - oci.platform.io
  resources:
  - replications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oci.platform.io
  resources:
  - replications/finalizers
  verbs:
  - update
- apiGroups:
  - oci.platform.io
  resources:
  - replications/status
  verbs:
  - get
  - patch
  - update
