apiVersion: oci.platform.io/v1beta1
kind: Replication
metadata:
  labels:
    app.kubernetes.io/name: mirror-image
    app.kubernetes.io/managed-by: kustomize
  name: replication-sample-beta
spec:
  # TODO(user): Add fields here
  destination:
    repoUrl: "usdo.ocir.io/tenancy/repo"
    #secretName: "artifact-registry"
  source:
    repoUrl: "linuxarpan/function"
    #secretName: "artifact-registry"
  pollingInterval: "1m"
  filterCriteria: ".*"
#    overWrite: false
#    maxChunkPerCount: 5

