apiVersion: oci.platform.io/v1beta1
kind: Replication
metadata:
  labels:
    app.kubernetes.io/name: mirror-image
    app.kubernetes.io/managed-by: kustomize
  name: replication-sample-second
spec:
  # TODO(user): Add fields here
  destination:
    repoUrl: "linuxarpan/function"
    # secretName: "regcred"
  source:
    repoUrl: "linuxarpan/testpush"
    secretName: "regcred"
  pollingInterval: "2m"
  filterCriteria: ".*"
#    overWrite: false
#    maxChunkPerCount: 5

